# Generated by Django 4.2.1 on 2023-05-25 11:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_answertask_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='answertask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
