# Generated by Django 4.2.1 on 2023-05-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_answertask_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintest',
            name='type',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
